- hosts: pywaw.org
  remote_user: root
  vars_files:
  - ../vars/main.yml
  - ../vars/{{ settings }}.yml
  - ../vars/secret.yml
  - ../vars/secret_{{ settings }}.yml
  - ../vars/envs.yml
  tasks:
  - name: install server requirements
    apt: name={{ item }}
    with_items:
      - nginx
      - python-virtualenv
      - git
      - libpq-dev
      - python3.5
      - python3.5-dev
      - gcc
      - postgresql-9.4
      - python-psycopg2
      - supervisor
      - gcc
      - nodejs
      - npm
  - name: configure uwsgi
    template: src=../templates/uwsgi.j2 dest=/etc/uwsgi/apps-supervisord/{{ project }}_{{ settings }}.yaml
    notify:
    - restart uwsgi
  - name: configure supervisor for uwsgi
    action: template src=../templates/supervisord.j2 dest=/etc/supervisor/conf.d/{{ project }}_{{ settings }}.conf
    notify:
    - restart supervisor
  - name: create project structure
    file: path={{ app_path }} state=directory
    remote_user: app
  - name: create project virtualenv
    command: virtualenv -p {{ python }} {{ virtualenv_path }} creates={{ virtualenv_path }}
    remote_user: app
  - name: create node bin link
    file: state=link src=/usr/bin/nodejs path=/usr/bin/node
  - name: create database
    action: postgresql_db db={{ db_name }}
    sudo: yes
    sudo_user: postgres
  - name: create database user
    action: postgresql_user db={{ db_name }} user={{ db_user }} password={{ db_password }} priv=ALL
    sudo: yes
    sudo_user: postgres
  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
  - name: restart supervisor
    service: name=supervisor state=restarted
  - name: restart uwsgi
    file: path=/tmp/{{ project }}_{{ settings }}.reload state=touch
