- hosts: pywaw.org
  remote_user: root
  tasks:
  - name: add authorized keys for root user
    authorized_key: user=root key="{{ lookup('file', item) }}"
    with_fileglob:
      - ../artefacts/authorized_keys/root/*
  - name: create app user
    user: name=app shell=/bin/bash
  - name: add authorized keys for app user
    authorized_key: user=app key="{{ lookup('file', item) }}"
    with_fileglob:
      - ../artefacts/authorized_keys/app/*
