- hosts: pywaw.org
  remote_user: root
  vars_files:
  - ../vars/main.yml
  - ../vars/{{ settings }}.yml
  tasks:
  - name: configure nginx site
    action: template src=../templates/nginx_site.j2 dest=/etc/nginx/sites-available/summit_{{ settings }}_common
    notify:
    - restart nginx
  - name: enable nginx site
    action: file src=/etc/nginx/sites-available/summit_{{ settings }}_common path=/etc/nginx/sites-enabled/summit_{{ settings }}_common state=link
    notify:
    - restart nginx
  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
